### PR TITLE
Frontpage stats

### PR DESCRIPTION
**Pull request by dwick**
:eyeglasses: @zeantsoi @rram 

instrumented some more things in statsd to help with the debugging

### CODE REVIEW

**Comment by zeantsoi** [comment]
Stats make sense. Would it be better to abstract into a separate function so that it could be invoked as a one-liner? Something like:

    # function definition
    def frontpage_stat(stat, targeting_frontpage)
        if targeting_frontpage:
            g.stats.simple_event("adzerk.frontpage_target.request.%s" % stat)

    # example function invocation
    frontpage_stat('refused', targeting_frontpage)

**Comment by zeantsoi** [comment]
:nail_care:

**Comment by rram** [comment]
Sorry, I don't have time for this. I've nominated @bsimpson63 in my place :runner:

**Comment by bsimpson63** [comment]
:nail_care:

**Comment by dwick** [comment]
@bsimpson63 since I'm trying to figure out what's going on with frontpage under delivery as much info as possible is helpful

:haircut:

**Comment by bsimpson63** [comment]
no_decisions/no_promo is still redundant right?

**Comment by dwick** [comment]
I think it's useful to not have to subtract all the connection errors to figure out if it was an error or adzerk actually came back with nothing. (coming back with nothing is what i'm most interested in)

**Comment by dwick** [comment]
:haircut:

**Comment by bsimpson63** [comment]
:fish:

**Pull request closed without merging**
