### PR TITLE
Add unit tests for queries and utils

### PR DESCRIPTION
**Pull request by zeantsoi**
:eyeglasses: @dwick @bsimpson63 

Just a few trivial unit tests on the `adzerk_utils.py` module. I intended to add to this in time, but for now, everything passes. It's not very interesting at the moment (there's not a whole lot to mock), but feel free to suggest any other tests you'd like to see.

### CODE REVIEW

**Comment by dwick** [comment]
Was kind of hoping for some test like this: https://gist.github.com/zeantsoi/7c86431ce348330f0db6#file-version_calculation-py-L64-L88

**Comment by zeantsoi** [comment]
Yup, can do. I'll just leave this open and eyeglass when they're in.

**Comment by dwick** [comment]
sounds good.

**Comment by zeantsoi** [comment]
:eyeglasses: @dwick @bsimpson63 

Re-opening: comprehensively tests the construction of Adzerk queries and covers the `adzerk_utils` module.

To try this out, you'll need to run `nosetests` or whatever test runner from within the `reddit-plugin-adzerk` plugin.

**Comment by dwick** [comment]
:fish: :+1:

**Comment by zeantsoi** [comment]
49f079cad94b86537671dd8a239df0b6a61c04a5

**Pull request closed without merging**
