### PR TITLE
adzerk API events

### PR DESCRIPTION
**Pull request by dwick**
:eyeglasses: @tsegaran @drunken-economist 

This PR builds on what @zeantsoi started here: https://github.com/reddit/reddit-plugin-adzerk/pull/158

I removed most of the fields outside of the request payload since those are covered by https://reddit.atlassian.net/wiki/display/DA/Self+Serve+Events.  The goal of these events are to be API focused and help us debug problems with calls made to adzerk.

Here is a sample event (docs inline):
```js
{  
   "ip":"0.0.0.0",
   "event":{  
      "event_ts":1459391029911,
      "event_topic":"adzerk_api_events",
      "uuid":"f930e67d-1fdf-4a6c-924d-eaa447673a45",
      "event_type":"ss.update_flight_request",
      "payload":{  
         "is_paused":false, // if the campaign is paused or not (flight upserts only)
         "is_automated":true, // system triggered update (user_id and user_name would be present otherwise)
         "is_deleted":false, // if the thing is deleted or not
         "request_body":{  // request body sent to adzerk
            "OptionType":1,
            "EndDate":"/Date(1459828800000)/",
            "IsUnlimited":false,
            "GoalType":1,
            "CustomTargeting":"",
            "Price":1.5,
            "CampaignId":383422,
            "SiteZoneTargeting":[  
               {  
                  "FlightId":1248673,
                  "IsExclude":"foo",
                  "SiteId":24950,
                  "ZoneId":null
               }
            ],
            "RateType":2,
            "IsFreqCap":null,
            "PriorityId":75302,
            "IsFullSpeed":false,
            "GeoTargeting":[  

            ],
            "IsActive":true,
            "Keywords":"wickads",
            "Impressions":133500,
            "StartDate":"/Date(1459224900000)/",
            "IsDeleted":false
         },
         "error_body":"{\"message\":\"Error converting value \\\"foo\\\" to type 'System.Boolean'. Path 'SiteZoneTargeting[0].IsExclude', line 1, position 395.\"}", // response body if the request errors (optional)
         "target_type":"PromoCampaign", // type of the `Thing` used to derive the adzerk request
         "is_overdelivered":false, // if the campaign is over delivered or not (flight upserts only)
         "requires_approval":false, // if the campaign requires approval before serving (flight upserts only)
         "error_status_code":400, // status code if the request errors (optional)
         "target_fullname":"t8_nba1", // thing fullname of the object used to derive the adzerk request
         "requires_payment":false // if the campaign requires payment (flight upserts only)
      }
   },
   "time":"2016-03-31T02:23:50.957396"
}
```

### CODE REVIEW

**Comment by dwick** [comment]
Added more events and updated the spec: https://reddit.atlassian.net/wiki/display/DA/Adzerk+API+Events

**Comment by tsegaran** [comment]
:fish: 
Looks good

**Comment by drunken-economist** [comment]
:fish: :fish:

**Comment by dwick** [comment]
c80d228

**Pull request closed without merging**
