### PR TITLE
Send DNT header to adzerk

### PR DESCRIPTION
**Pull request by dwick**
:eyeglasses: @zeantsoi

### CODE REVIEW

**Comment by zeantsoi** [comment]
:fish:

**Comment by dwick** [comment]
:haircut: added feature flag

**Comment by zeantsoi** [comment]
Can you reference the config change?

**Comment by dwick** [comment]
https://github.com/reddit/reddit-private/pull/1079

**Comment by zeantsoi** [comment]
Why would this need to be an employee-only function? Seems like it's a better candidate for a boolean on/off toggle, is it not?

**Comment by dwick** [comment]
for testing

**Comment by zeantsoi** [comment]
:fish:

**Comment by dwick** [comment]
:haircut: added some more stuff:

- use the DNT domains for static/engine
- set `IsNoTrack` on selfserve creatives that dont have 3rd party trackers

**Comment by zeantsoi** [comment]
:nail_care: just a few comments.

**Comment by dwick** [comment]
:haircut:

**Comment by zeantsoi** [comment]
Looks like you have us loading jQuery from the `jquery.js` static file. Will this change be uniform across all pages on reddit that use jQuery?

**Comment by zeantsoi** [comment]
:nail_care:

**Comment by dwick** [comment]
this jquery is only for the ads, i've moved it to make that more clear and ensure there's no overwriting going on because of the weirdness of plugin's static handling

**Comment by dwick** [comment]
:haircut:

**Comment by zeantsoi** [comment]
:fish:

**Comment by dwick** [comment]
I've split this up into multiple commits so I can deploy things piece by piece (per adzerk's request)

**Comment by dwick** [comment]
d674252b997b15f474c8a7acc8f966b1aa3c66bc
ee78ea0c6e51e8b56447c0995f83777de6e82948
33981e4b899cdad576f38e6684d4d96890491905

deployed so far

**Comment by dwick** [comment]
f1a1b657f2044b5541f9fabc234c211fc66e44b5

**Comment by dwick** [comment]
b77fba181a19c1db8a458962891486452881ad3f

**Pull request closed without merging**
