### PR TITLE
Remove "discuss this ad on reddit" link from banner ads

### PR DESCRIPTION
**Pull request by zeantsoi**
👓 @dwick 

Re: [reddit-public #5627](https://github.com/reddit/reddit-public/pull/5627).

[Live on my staging](https://zeantsoi.staging.snooguts.net).

### CODE REVIEW

**Comment by dwick** [comment]
this entire method can be removed: https://github.com/reddit/reddit-plugin-adzerk/pull/221/files#diff-57febd409643579a52cda50d3cf8b9b2L48

also everywhere it's called:
https://github.com/reddit/reddit-plugin-adzerk/blob/0720dc8968604a9de3ef294001788f7bbd98e41d/reddit_adzerk/templates/ad300x250.html#L23
https://github.com/reddit/reddit-plugin-adzerk/blob/0720dc8968604a9de3ef294001788f7bbd98e41d/reddit_adzerk/templates/ad300x250companion.html#L10

💅

**Comment by zeantsoi** [comment]
💇 indeed.

**Comment by dwick** [comment]
🐟!

**Comment by zeantsoi** [comment]
https://github.com/reddit/reddit-plugin-adzerk/commit/b371861f911f093005d6b2b51a5d5889b68b0dd1

**Pull request closed without merging**
